### ISSUE TITLE
Pill tracker

### ISSUE THREAD

**Issue by brianhanifin** [brianhanifin/Home-Assistant-Config#19]
https://github.com/dale3h/homeassistant-config/blob/master/examples/packages/pill_tracker.yaml

**Comment by brianhanifin** [comment]
Commit https://github.com/brianhanifin/Home-Assistant-Config/commit/5c1ff640ba74b834be26844e5bb826243a6a8cf8 resolved this with a physical Xiaomi button.

**Comment by CCOSTAN** [comment]
Hey @brianhanifin , This might be of interest to you - 

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/ios.yaml#L33-L119

Code to see if you are home or not and then remind you to take/give medicine when you are actually home.

**Comment by brianhanifin** [comment]
>Hey @brianhanifin , This might be of interest to you -  ...

@CCOSTAN Thanks for the tip. For now I am only using this to track the dog's ceisure medicine, but I have considered putting a Xiaomi button next to my pills as well.

Now that I think about it, I have an alexa reminder set to run at a time that I am hopefully home after dropping the boys off at school. But I could have that announcement happen as soon as I get home. You've given me something to think about. :)

**Comment by CCOSTAN** [comment]
Here is how I used the DASH BUTTON by my pill Box. 
https://youtu.be/rwQVe6sIi9w?t=81
