### ISSUE TITLE
Google Drive Link is Down(ish)

### ISSUE THREAD

**Issue by kschlichter** [brianhanifin/Home-Assistant-Config#57]
The Google Spreadsheet under "calculation references" comes up with an error that the "file is in the owner's trash."  I put an alternative together that corrects some of the math in the original and handles the lzw30 separately.  If you're interested in changing the link:

https://docs.google.com/spreadsheets/d/14wTP4OL4hkDK3Et5kYL4fyxPIK_R9JR3cgFxSa6dhyw/edit#gid=0

**Comment by brianhanifin** [comment]
Thanks for the heads up Kevin! I made a public copy available and have replaced the link at the top of the script.
