### ISSUE TITLE
Updating LED Notification scritpt to support Zwave_JS

### ISSUE THREAD

**Issue by millercentral** [brianhanifin/Home-Assistant-Config#60]
Just wondering now that the Zwave JS integration support configuration updates if you might update your cool script for updating the LED on inovelli switches?

**Comment by brianhanifin** [comment]
I want to. I wasn't able to get the new multi step code to work initially. Coincidentally my leds were flashing last night (I don't know why) so I was going to look into it further today. Perhaps a recent a Zwave JS update resolved it?

Unfortunately a power outage corrupted a drive on my server. So I won't be able to look into it for a couple of days.

**Comment by millercentral** [comment]
Sorry about the server drive corruption! I noticed in the current release that under "configure" in the device list for the inovelli switch there are options to set the LED type:
![image](https://user-images.githubusercontent.com/7720102/115790552-bcdf7c80-a37b-11eb-91f6-640f982fa304.png)

Not sure how that maps to the scripting though. If there is anything I can do to assist, please let me know. Take care.

**Comment by brianhanifin** [comment]
Sorry, I forgot to update this issue. I updated the forum post. Anyway, this version appears to be working for me.
https://github.com/brianhanifin/Home-Assistant-Config/blob/31192cfeaa8eb0125cd530f5fcc5586b98352ec7/scripts/notifications/inovelli_led/inovelli_led.yaml
